export const SETLOADING = 'SETLOADING'
export const SETDEFINITIONS = 'SETDEFINITIONS'
export const SETKEYWORD = 'SETKEYWORD'
export const SETSEARCHPOSITION = 'SETSEARCHPOSITION'
export const SETIMAGES = 'SETIMAGES'

